general_plotting:
    context: notebook
    style: white
    palette: Paired
    font: sans-serif
    font_scale: 1.4
    color_codes: False
    rc:
        figure.frameon: True
        axes.grid: False
        axes.spines.top: True
        axes.spines.right: True
        axes.labelsize: 25
        xtick.top: True
        xtick.bottom: True
        ytick.left: True
        ytick.right: True
        xtick.direction: in
        ytick.direction: in
        font.weight: normal 
        savefig.dpi: 300
        savefig.transparent: False

settings_scatterplots:
    marker: o
    s: 70
    edgecolor: black
    alpha: 0.7
settings_errorbars:
    marker: o
    markersize: 15
    markeredgecolor: black
    elinewidth: 3
    capsize: 5
    linestyle: ''
settings_pointplots:
    linestyles: '-'
    scale: 1.5
    capsize: 0.2
    errwidth: 3
    ci: sd
settings_barplots:
    edgecolor: black
    capsize: 0.2
    errwidth: 2
    ci: sd
settings_stackedbars:
    edgecolor: black
    capsize: 4
    alpha: 0.7
settings_clustermap:
    method: average
    col_cluster: False
    linewidths: 1
    linecolor: white
    cmap: coolwarm
    robust: True
    fmt: .2f
    annot_kws: 
        fontsize: 12
settings_diagonal:
    linestyle: '--'
    color: gray